name: Exemplo Artifact
run-name: Exemplo workflow para Artifact, executado por ${{ github.actor }}
on:
  workflow_dispatch:
jobs:
    upload-artifact:
        runs-on: ubuntu-latest
        steps:
          - name: Listando arquivos
            run: ls
          - name: Gerar alguns arquivos
            run: |
              mkdir artefatos
              echo "Arquivo de teste 01" > ./artefatos/primeiro_arquivo.txt
              echo "Arquivo de teste 02" > ./artefatos/segundo_arquivo.txt
              echo "Arquivo de teste 03" > ./artefatos/terceiro_arquivo.txt
              echo "Arquivo de teste 04" > ./artefatos/quarto_arquivo.txt

        