name: Workflow concorrencia
run-name: Workflow Concorrencia ${{ github.run_number }}
on:
    push:

concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}
    cancel-in-progress: true

jobs:
    exemplo-fluxo-execucao-01:
        runs-on: ubuntu-latest
        steps:
            -   name: Execução do job teste
                run: |
                    sleep 120;
                    echo "Action executada job 01"
    
    exemplo-fluxo-execucao-02:
        runs-on: ubuntu-latest
        needs: [exemplo-fluxo-execucao-01]
        steps:
            -   name: Execução do job teste
                run: |
                    sleep 120;
                    echo "Action executada job 01"
