name: Workflow Controle Execucao
on:
    push:
jobs:
    apenas-main:
        if: ${{ github.ref == 'refs/heads/main'}}
        name: Esse job só executa na branch main
        runs-on: ubuntu-latest
        steps:
            -   name: Executando na main
                run: echo "Executando na main"
    todos:
        runs-on: ubuntu-latest
        steps:
            -   name: Execução em Feature
                if: ${{ contains(github.ref, 'refs/heads/feature') }}
                run: echo "Execução em Feature"
            -   name: Execução em Main 
                if: ${{ github.ref == 'refs/heads/main' }}
                run: echo "Execução em Main"
            -   name: Envio de Erros
                if: ${{ failure() }}
                run: echo "Envio de erro"