name: Workflow Controle Execucao
on:
    push:
jobs:
    apenas-main:
        if: ${{ github.ref == 'refs/heads/main'}}
        name: Esse job sรณ executa na branch main
        runs-on: ubuntu-latest
        steps:
            -   name: Executando na main
                run: echo "Executando na main"