name: Schedule e Inputs
on:
    #schedule:
    #    -   cron: "*/2 * * * *"
    workflow_dispatch:
jobs:
    teste:
        permissions: write-all
        runs-on: ubuntu-latest
        steps:
            -   name: Action de Teste
                run: echo "Action executada apenas em main e features!"