name: Workflow Evento
on:
    push:
        branches: ["main", "feature/*"]
        #paths-ignore: 
        paths:
            - "src/**"
        tags:
            - v*
jobs:
    teste:
        runs-on: ubuntu-latest
        steps:
            -   name: Action de Teste
                run: echo "Action executada apenas em main e features!"
